version: "3.9"

services:

  backend:
    build: ./backend
    container_name: devops-backend

    env_file:
      - .env

    ports:
      - "8000:8000"

    environment:
      - GITHUB_TOKEN=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 

    networks:
      - devops-net

networks:
  devops-net: