version: "3.9"

services:

  backend:
    build: ./backend
    container_name: devops-backend

    env_file:
      - .env

    ports:
      - "8000:8000"

    environment:
      - GITHUB_TOKEN=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
      - GITLAB_TOKEN=glpat-jpHH2VuvFBgOQKZGl8XdSG86MQp1OjZoNHA1Cw.01.121ruywcz

    networks:
      - devops-net

networks:
  devops-net: